"""added cover pic link

Revision ID: 13e03682ca06
Revises: 2b687b9f7107
Create Date: 2019-12-23 19:31:36.623062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e03682ca06'
down_revision = '2b687b9f7107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('cover_pic_link', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'cover_pic_link')
    # ### end Alembic commands ###
