"""added pic credits

Revision ID: 2b687b9f7107
Revises: 659eda350e69
Create Date: 2019-12-16 23:16:48.005473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b687b9f7107'
down_revision = '659eda350e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('cover_pic_credit', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'cover_pic_credit')
    # ### end Alembic commands ###
