"""empty message

Revision ID: c186f8d2bb0f
Revises: 
Create Date: 2019-12-03 17:25:46.704403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c186f8d2bb0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('date_quarantined', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'date_quarantined')
    # ### end Alembic commands ###
