"""empty message

Revision ID: 0b61cca43bb1
Revises: 36e5328e6d00
Create Date: 2019-11-17 13:42:32.832448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b61cca43bb1'
down_revision = '36e5328e6d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('submission_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_project_submission_date'), 'project', ['submission_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_submission_date'), table_name='project')
    op.drop_column('project', 'submission_date')
    # ### end Alembic commands ###
