"""empty message

Revision ID: 1794fedce9b8
Revises: 5bda56e351d8
Create Date: 2019-11-16 15:07:55.576260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1794fedce9b8'
down_revision = '5bda56e351d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('downvotes', sa.Column('project_id', sa.Integer(), nullable=True))
    op.drop_constraint('downvotes_ibfk_1', 'downvotes', type_='foreignkey')
    op.create_foreign_key(None, 'downvotes', 'project', ['project_id'], ['id'])
    op.drop_column('downvotes', 'post_id')
    op.add_column('upvotes', sa.Column('project_id', sa.Integer(), nullable=True))
    op.drop_constraint('upvotes_ibfk_1', 'upvotes', type_='foreignkey')
    op.create_foreign_key(None, 'upvotes', 'project', ['project_id'], ['id'])
    op.drop_column('upvotes', 'post_id')
    op.add_column('votes', sa.Column('project_id', sa.Integer(), nullable=True))
    op.drop_constraint('votes_ibfk_1', 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'project', ['project_id'], ['id'])
    op.drop_column('votes', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key('votes_ibfk_1', 'votes', 'project', ['post_id'], ['id'])
    op.drop_column('votes', 'project_id')
    op.add_column('upvotes', sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.create_foreign_key('upvotes_ibfk_1', 'upvotes', 'project', ['post_id'], ['id'])
    op.drop_column('upvotes', 'project_id')
    op.add_column('downvotes', sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    op.create_foreign_key('downvotes_ibfk_1', 'downvotes', 'project', ['post_id'], ['id'])
    op.drop_column('downvotes', 'project_id')
    op.drop_table('library')
    # ### end Alembic commands ###
