"""empty message

Revision ID: 1f1ec46615dc
Revises: 971f7b8e5e6b
Create Date: 2019-11-20 11:03:40.507431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1ec46615dc'
down_revision = '971f7b8e5e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('date_seek_review', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_project_date_seek_review'), 'project', ['date_seek_review'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_date_seek_review'), table_name='project')
    op.drop_column('project', 'date_seek_review')
    # ### end Alembic commands ###
