"""added login for fb and twitter

Revision ID: 4b04718bda7c
Revises: 13e03682ca06
Create Date: 2020-01-25 18:54:29.448518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b04718bda7c'
down_revision = '13e03682ca06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('facebook_id', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('twitter_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'twitter_id')
    op.drop_column('user', 'facebook_id')
    # ### end Alembic commands ###
