"""added chpaters model

Revision ID: 5bda56e351d8
Revises: dccb2af6f977
Create Date: 2019-11-13 11:12:47.439239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bda56e351d8'
down_revision = 'dccb2af6f977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_no', sa.Integer(), nullable=True),
    sa.Column('chapter_title', sa.Text(length=5000), nullable=True),
    sa.Column('chapter_body', sa.String(length=4294000000), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_date_submitted'), 'chapter', ['date_submitted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapter_date_submitted'), table_name='chapter')
    op.drop_table('chapter')
    # ### end Alembic commands ###
