"""added project cover pic

Revision ID: 659eda350e69
Revises: 2343089bd407
Create Date: 2019-12-16 20:41:21.090473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659eda350e69'
down_revision = '2343089bd407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('cover_pic', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'cover_pic')
    # ### end Alembic commands ###
