"""empty message

Revision ID: 971f7b8e5e6b
Revises: c754957ccd4c
Create Date: 2019-11-19 10:53:18.930682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971f7b8e5e6b'
down_revision = 'c754957ccd4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('rating', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rating_timestamp'), 'rating', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'rating', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_index(op.f('ix_rating_timestamp'), table_name='rating')
    op.drop_column('rating', 'user_id')
    op.drop_column('rating', 'timestamp')
    # ### end Alembic commands ###
