"""empty message

Revision ID: 98ce982cfb13
Revises: 
Create Date: 2020-05-10 11:07:29.547450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ce982cfb13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('cover_pic', sa.String(length=1000), nullable=True))
    op.add_column('project', sa.Column('cover_pic_credit', sa.String(length=1000), nullable=True))
    op.add_column('project', sa.Column('cover_pic_link', sa.String(length=1000), nullable=True))
    op.add_column('project', sa.Column('date_quarantined', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('facebook_id', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('profile_pic', sa.String(length=1000), nullable=True))
    op.add_column('user', sa.Column('twitter_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'twitter_id')
    op.drop_column('user', 'profile_pic')
    op.drop_column('user', 'facebook_id')
    op.drop_column('project', 'date_quarantined')
    op.drop_column('project', 'cover_pic_link')
    op.drop_column('project', 'cover_pic_credit')
    op.drop_column('project', 'cover_pic')
    # ### end Alembic commands ###
