"""empty message

Revision ID: d9fba8a10181
Revises: 0b61cca43bb1
Create Date: 2019-11-18 09:20:08.968451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9fba8a10181'
down_revision = '0b61cca43bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('date_published', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_project_date_published'), 'project', ['date_published'], unique=False)
    op.drop_index('ix_project_submission_date', table_name='project')
    op.drop_column('project', 'submission_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('submission_date', mysql.DATETIME(), nullable=True))
    op.create_index('ix_project_submission_date', 'project', ['submission_date'], unique=False)
    op.drop_index(op.f('ix_project_date_published'), table_name='project')
    op.drop_column('project', 'date_published')
    # ### end Alembic commands ###
